[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
autostart=true
autorestart=true
stderr_logfile=/var/log/nginx/error.log
stdout_logfile=/var/log/nginx/access.log

[program:gunicorn]
command=gunicorn --bind 127.0.0.1:5002 --workers 2 --timeout 120 site_app:app
directory=/app
autostart=true
autorestart=true
stderr_logfile=/var/log/gunicorn/error.log
stdout_logfile=/var/log/gunicorn/access.log
